blank_issues_enabled: false
contact_links:
  - name: Read the CONTRIBUTING guide
    url: https://github.com/SirSnorealot/Pokemon-Tomy-Database/blob/main/CONTRIBUTING.md
    about: Please review how toy IDs and image paths work before opening an issue.
